server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#      关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ming.entity

