server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql//localhost:3306/seckill?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    &zeroDateTimeBehavior=convertToNull&useSSL=false
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ming.entity